name: Test
on:
  pull_request:
    types: [opened]
  workflow_dispatch :
env :
  API_URL : "https://int.api.zscwp.io"
  AUTH_URL : "https://z-cwp-int.us.auth0.com"
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
     - name: Configure AWS credentials from Test account
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v1

     - name: Terraform Format
       id: fmt
       run: terraform fmt -check

     - name: Terraform Init
       id: init
       run: terraform init
      
     - name: Terraform Validate
       id: validate
       run: terraform validate -no-color

     - name: Terraform Plan
       id: plan
       if: github.event_name == 'pull_request'
       run: terraform plan -no-color -var="grafana_idp_metadata_url=${{ secrets.GRAFANA_IDP_METADATA_URL }}" -var="opensearch_idp_metadata_content=${{ secrets.OPENSEARCH_IDP_METADATA_CONTENT }}" -var="opensearch_idp_entity_id=${{ secrets.OPENSEARCH_IDP_ENTITY_ID }}" -var="opensearch_idp_metadata_location=${{ secrets.OPENSEARCH_IDP_METADATA_LOCATION }}"
       continue-on-error: true
     - name: checkout   
       uses: actions/checkout@v2
     - name: Iac-scan  
       uses : ZscalerCWP/Zscaler-IaC-Action@main
       id : iac-scan
       with:
          client_id : ${{ secrets.ZSCANNER_CLIENT_ID }}
          client_secret : ${{ secrets.ZSCANNER_CLIENT_SECRET }}
          fail_build : 'true'
          output_format : 'human+github-sarif'
          region : 'CUSTOM'
          log_level : 'debug'
          run : echo ${{ steps.iac-scan.outputs.sarif_file_path }}
     - name: Upload SARIF file
       if: ${{ success() || failure() && (steps.iac-scan.outputs.sarif_file_path != '') }}
       uses: github/codeql-action/upload-sarif@v1
       with:
          sarif_file: ${{ steps.iac-scan.outputs.sarif_file_path }}
