name: Test
on:
  pull_request:
    types: [opened]
  workflow_dispatch :
env :
  API_URL : "https://int.api.zscwp.io"
  AUTH_URL : "https://z-cwp-int.us.auth0.com"
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
     - name: Configure AWS credentials from Test account
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
     - name: checkout   
       uses: actions/checkout@v2
       
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v1

     - name: Terraform Init
       id: init
       run: terraform init
      
     - name: Terraform Validate
       id: validate
       run: terraform validate -no-color

     - name: Terraform Plan
       id: plan
       run: terraform plan -out tfplanout.binary -var="aws_access_key=aws-access-key-id" -var="aws_secret_key=aws-secret-access-key"
       continue-on-error: true
   
     - name: Terraform Show
       id: show
       run: terraform show -json './tfplanout.binary' > tfplan.json
       continue-on-error: true
     - name: Iac-scan  
       uses : ZscalerCWP/Zscaler-IaC-Action@main
       id : iac-scan
       with:
          client_id : ${{ secrets.ZSCANNER_CLIENT_ID }}
          client_secret : ${{ secrets.ZSCANNER_CLIENT_SECRET }}
          fail_build : 'true'
          output_format : 'human+github-sarif'
          region : 'CUSTOM'
          log_level : 'debug'
          run : echo ${{ steps.iac-scan.outputs.sarif_file_path }}
     - name: Upload SARIF file
       if: ${{ success() || failure() && (steps.iac-scan.outputs.sarif_file_path != '') }}
       uses: github/codeql-action/upload-sarif@v1
       with:
          sarif_file: ${{ steps.iac-scan.outputs.sarif_file_path }}
